import {
    Activity,
    AlertTriangle,
    ArrowRightLeft,
    Award,
    BarChart3,
    BookUser,
    Box,
    Boxes,
    CalendarClock,
    ChartArea,
    CircleDollarSign,
    ClipboardList,
    FileBarChart,
    FileCheck,
    Gauge,
    GitBranch,
    History,
    Home,
    Inbox,
    Landmark,
    LayoutTemplate,
    LineChart,
    Megaphone,
    Network,
    Package,
    Percent,
    PhoneCall,
    PieChart,
    Plug,
    Receipt,
    RefreshCw,
    Settings,
    Share2,
    Store,
    Table2,
    Target,
    TrendingUp,
    Trophy,
    Truck,
    UserPlus,
    Users,
    Wallet,
    Warehouse,
} from 'lucide-react';

export const navigationIcons = {
    activity: Activity,
    'alert-triangle': AlertTriangle,
    'arrow-right-left': ArrowRightLeft,
    award: Award,
    'bar-chart-3': BarChart3,
    'book-user': BookUser,
    box: Box,
    boxes: Boxes,
    'calendar-clock': CalendarClock,
    'chart-area': ChartArea,
    'circle-dollar-sign': CircleDollarSign,
    'clipboard-list': ClipboardList,
    'file-bar-chart': FileBarChart,
    'file-check': FileCheck,
    gauge: Gauge,
    'git-branch': GitBranch,
    history: History,
    home: Home,
    inbox: Inbox,
    landmark: Landmark,
    'layout-template': LayoutTemplate,
    'line-chart': LineChart,
    megaphone: Megaphone,
    network: Network,
    package: Package,
    percent: Percent,
    'phone-call': PhoneCall,
    'pie-chart': PieChart,
    plug: Plug,
    receipt: Receipt,
    'refresh-cw': RefreshCw,
    settings: Settings,
    share2: Share2,
    store: Store,
    'table-2': Table2,
    target: Target,
    'trending-up': TrendingUp,
    trophy: Trophy,
    truck: Truck,
    'user-plus': UserPlus,
    users: Users,
    wallet: Wallet,
    warehouse: Warehouse,
};
