import {
    Activity,
    AlertTriangle,
    BarChart3,
    ClipboardList,
    FileCheck,
    GitBranch,
    Home,
    LineChart,
    Megaphone,
    Network,
    Package,
    PhoneCall,
    Plug,
    RefreshCw,
    Settings,
    Target,
    Trophy,
    Truck,
    Users,
    Wallet,
    Warehouse,
} from 'lucide-react';

export const navigationIcons = {
    activity: Activity,
    'alert-triangle': AlertTriangle,
    'bar-chart-3': BarChart3,
    'clipboard-list': ClipboardList,
    'file-check': FileCheck,
    'git-branch': GitBranch,
    home: Home,
    'line-chart': LineChart,
    megaphone: Megaphone,
    network: Network,
    package: Package,
    'phone-call': PhoneCall,
    plug: Plug,
    'refresh-cw': RefreshCw,
    settings: Settings,
    target: Target,
    trophy: Trophy,
    truck: Truck,
    users: Users,
    wallet: Wallet,
    warehouse: Warehouse,
};
