#!/usr/bin/env bash
# ONE-SHOT root hardening for salesloop.vn (app host).
# Run: sudo bash deploy/ops-harden-root.sh
# Safe-ish to re-run. Does NOT wipe existing UFW allow rules blindly.
set -euo pipefail

APP_DIR="${APP_DIR:-/var/www/erm-pushsale}"
BACKUP_ROOT="${BACKUP_ROOT:-/var/backups/erm-pushsale}"
DEPLOY_USER="${DEPLOY_USER:-deploy}"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "Run as root: sudo bash $0" >&2
  exit 1
fi

echo "=== 1. Packages ==="
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y fail2ban mysql-client ufw curl ca-certificates unattended-upgrades

echo "=== 2. Backup directory ==="
mkdir -p "$BACKUP_ROOT"
chown "${DEPLOY_USER}:www-data" "$BACKUP_ROOT"
chmod 750 "$BACKUP_ROOT"
# Also keep deploy home path as symlink-friendly alt
mkdir -p "/home/${DEPLOY_USER}/backups"
ln -sfn "$BACKUP_ROOT" "/home/${DEPLOY_USER}/backups/erm-pushsale"
chown -h "${DEPLOY_USER}:${DEPLOY_USER}" "/home/${DEPLOY_USER}/backups/erm-pushsale" || true

echo "=== 3. Laravel scheduler cron + packages ==="
apt-get install -y cron
systemctl enable --now cron
cat >/etc/cron.d/erm-pushsale-scheduler <<EOF
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
* * * * * ${DEPLOY_USER} cd ${APP_DIR} && /usr/bin/php artisan schedule:run >> ${APP_DIR}/storage/logs/scheduler.log 2>&1
EOF
chmod 644 /etc/cron.d/erm-pushsale-scheduler

# Ensure Laravel storage dirs exist
sudo -u www-data mkdir -p "${APP_DIR}/storage/app/public" "${APP_DIR}/storage/framework/cache" "${APP_DIR}/storage/framework/sessions" "${APP_DIR}/storage/framework/views" "${APP_DIR}/storage/logs" || true
chown -R deploy:www-data "${APP_DIR}/storage" || true
chmod -R ug+rwX "${APP_DIR}/storage" || true

echo "=== 4. Reverb bind localhost only (stop public :8080) ==="
REVERB_CONF=/etc/supervisor/conf.d/pushsale-reverb.conf
if [[ -f "$REVERB_CONF" ]]; then
  sed -i 's/--host=0\.0\.0\.0/--host=127.0.0.1/g' "$REVERB_CONF"
  supervisorctl reread || true
  supervisorctl update || true
  supervisorctl restart pushsale-reverb || true
fi

echo "=== 5. Nginx: rate limit + hide tokens + block sensitive paths ==="
mkdir -p /etc/nginx/conf.d
cat >/etc/nginx/conf.d/erm-security.conf <<'NGX'
# Generated by ops-harden-root.sh
server_tokens off;

limit_req_zone $binary_remote_addr zone=erm_login:10m rate=5r/s;
limit_req_zone $binary_remote_addr zone=erm_api:10m rate=20r/s;
limit_conn_zone $binary_remote_addr zone=erm_conn:10m;

# Shared map for bad bots (light)
map $http_user_agent $bad_bot {
    default 0;
    ~*(nikto|sqlmap|masscan|zgrab|nmap) 1;
}
NGX

SITE=/etc/nginx/sites-available/salesloop.vn
if [[ -f "$SITE" ]] && ! grep -q 'erm_security_locations' "$SITE"; then
  # Insert security locations before the generic location /
  python3 - <<'PY' || true
from pathlib import Path
p = Path("/etc/nginx/sites-available/salesloop.vn")
text = p.read_text()
snippet = """
    # erm_security_locations
    if ($bad_bot) { return 403; }
    location = /login {
        limit_req zone=erm_login burst=20 nodelay;
        try_files $uri /index.php?$query_string;
    }
    location ^~ /api/ {
        limit_req zone=erm_api burst=40 nodelay;
        try_files $uri /index.php?$query_string;
    }
    location ~* /(\\.env|\\.git|composer\\.(json|lock)|package(-lock)?\\.json|phpunit\\.xml) {
        deny all;
        return 404;
    }
    location ~* ^/(storage|vendor|node_modules|tests)/ {
        deny all;
        return 404;
    }
"""
needle = "    location / {"
if "erm_security_locations" not in text and needle in text:
    text = text.replace(needle, snippet + "\n" + needle, 1)
    p.write_text(text)
    print("Patched", p)
else:
    print("Skip site patch (already present or marker missing)")
PY
fi

nginx -t
systemctl reload nginx

echo "=== 6. UFW baseline (keep SSH — no reset) ==="
ufw default deny incoming || true
ufw default allow outgoing || true
ufw allow OpenSSH || true
ufw allow 22/tcp || true
ufw allow 80/tcp || true
ufw allow 443/tcp || true
# Reverb must stay localhost; deny accidental public exposure
ufw deny 8080/tcp || true
ufw --force enable
ufw status verbose

echo "=== 7. fail2ban ==="
cat >/etc/fail2ban/jail.d/erm-pushsale.conf <<'F2B'
[sshd]
enabled = true
port = ssh
filter = sshd
logpath = /var/log/auth.log
maxretry = 4
bantime = 1h
findtime = 10m

[nginx-http-auth]
enabled = true
port = http,https
logpath = /var/log/nginx/*error.log
maxretry = 5
bantime = 1h

[nginx-limit-req]
enabled = true
port = http,https
filter = nginx-limit-req
logpath = /var/log/nginx/*error.log
maxretry = 10
findtime = 5m
bantime = 30m
F2B
systemctl enable --now fail2ban
fail2ban-client reload || systemctl restart fail2ban
fail2ban-client status || true

echo "=== 8. SSH harden (key-only; keep deploy working) ==="
# Only apply if deploy can still key-auth (we already use keys).
mkdir -p /etc/ssh/sshd_config.d
cat >/etc/ssh/sshd_config.d/99-erm-harden.conf <<'SSH'
PermitRootLogin prohibit-password
PasswordAuthentication no
KbdInteractiveAuthentication no
X11Forwarding no
MaxAuthTries 4
AllowAgentForwarding no
SSH
sshd -t
systemctl reload ssh || systemctl reload sshd

echo "=== 9. App env + OPS_BACKUP_PATH ==="
cd "$APP_DIR"
if grep -q '^OPS_BACKUP_PATH=' .env; then
  sed -i "s#^OPS_BACKUP_PATH=.*#OPS_BACKUP_PATH=${BACKUP_ROOT}#" .env
else
  printf '\nOPS_BACKUP_PATH=%s\n' "$BACKUP_ROOT" >> .env
fi
# Ensure SESSION_SECURE etc.
bash "${APP_DIR}/deploy/harden-prod-env.sh" || true

echo "=== 10. First backup smoke ==="
sudo -u "$DEPLOY_USER" -H bash -lc "cd ${APP_DIR} && php artisan ops:backup --path=${BACKUP_ROOT}" || true
ls -lah "$BACKUP_ROOT" | head -20

echo "=== DONE — root harden complete ==="
echo "NEXT (manual, provider panel): create weekly SNAPSHOT for BOTH VMs:"
echo "  - App: 14.225.204.137 (salesloop.vn)"
echo "  - DB:  14.225.205.65"
echo "Optional: Cloudflare orange-cloud + WAF for DDoS L7."
