<?php

return [
    'sale-kpi' => [
        'menu_code' => '4.5.1',
        'title' => 'Sale KPI',
        'admin_path' => '/admin/sales/reports/sale-kpi',
        'route_name' => 'sales.reports.sale-kpi',
        'legacy_paths' => ['/ld/sale/sale-kpi'],
    ],
    'sale-closing-summary' => [
        'menu_code' => '4.5.2',
        'title' => 'Bảng tổng hợp chốt đơn',
        'admin_path' => '/admin/sales/reports/closing-summary',
        'route_name' => 'sales.reports.closing-summary',
        'legacy_paths' => ['/ld/sale/bang-tong-hop-ban-hang'],
    ],
    'sale-work' => [
        'menu_code' => '4.5.3',
        'title' => 'Báo cáo công việc sale',
        'admin_path' => '/admin/sales/reports/work',
        'route_name' => 'sales.reports.work',
        'legacy_paths' => ['/ld/sale/bao-cao/bao-cao-cong-viec-sale', '/ld/sale/bao-cao-cong-viec-sale'],
    ],
    'sale-revenue-detail' => [
        'menu_code' => '4.5.4',
        'title' => 'Báo cáo doanh số sale',
        'admin_path' => '/admin/sales/reports/revenue-detail',
        'route_name' => 'sales.reports.revenue-detail',
        'legacy_paths' => ['/ld/sale/bao-cao-doanh-so-chi-tiet', '/bao-cao/bao-cao-doanh-so-chi-tiet'],
    ],
    'sale-revenue' => [
        'menu_code' => '4.5.5',
        'title' => 'Báo cáo doanh số',
        'admin_path' => '/admin/sales/reports/revenue',
        'route_name' => 'sales.reports.revenue',
        'legacy_paths' => ['/ld/sale/bao-cao/bao-cao-doanh-so'],
    ],
    'sale-revenue-v2' => [
        'menu_code' => '4.5.6',
        'title' => 'Báo cáo doanh số V2',
        'admin_path' => '/admin/sales/reports/revenue-v2',
        'route_name' => 'sales.reports.revenue-v2',
        'legacy_paths' => ['/ld/sale/bao-cao/bao-cao-doanh-so-v2'],
    ],
    'sale-appointments' => [
        'menu_code' => '4.5.8',
        'title' => 'Báo cáo lịch hẹn telesales',
        'admin_path' => '/admin/sales/reports/appointments',
        'route_name' => 'sales.reports.appointments',
        'legacy_paths' => ['/ld/thong-ke/bao-cao-lich-hen-telesales'],
    ],
    'system-business' => [
        'menu_code' => '4.5.9',
        'title' => 'Báo cáo kinh doanh hệ thống',
        'admin_path' => '/admin/reports/system-business',
        'route_name' => 'reports.system-business',
        'legacy_paths' => ['/ld/thong-ke/bao-cao-kinh-doanh-he-thong'],
    ],
    'marketing-1' => [
        'menu_code' => '2.7.1',
        'title' => 'Báo cáo doanh số marketing',
        'admin_path' => '/admin/marketing/reports/revenue-detail',
        'route_name' => 'marketing.reports.revenue-detail',
        'legacy_paths' => ['/ld/marketing/bao-cao-doanh-so-chi-tiet-marketing', '/bao-cao/bao-cao-doanh-so-chi-tiet-marketing'],
    ],
    'marketing-sales-summary' => [
        'menu_code' => '2.7.2',
        'title' => 'Báo cáo doanh số',
        'admin_path' => '/admin/marketing/reports/revenue',
        'route_name' => 'marketing.reports.revenue',
        'legacy_paths' => ['/ld/marketing/bao-cao/bao-cao-doanh-so'],
    ],
    'marketing-sales-v2' => [
        'menu_code' => '2.7.3',
        'title' => 'Báo cáo doanh số V2',
        'admin_path' => '/admin/marketing/reports/revenue-v2',
        'route_name' => 'marketing.reports.revenue-v2',
        'legacy_paths' => ['/ld/marketing/bao-cao-doanh-so-v21'],
    ],
    'marketing-3' => [
        'menu_code' => '2.7.5',
        'title' => 'Báo cáo công việc',
        'admin_path' => '/admin/marketing/reports/work',
        'route_name' => 'marketing.reports.work',
        'legacy_paths' => ['/ld/thong-ke/bao-cao-cong-viec-mkt'],
    ],
    'marketing-4' => [
        'menu_code' => '8.1.3',
        'title' => 'Báo cáo up sale',
        'admin_path' => '/admin/marketing/reports/upsale',
        'route_name' => 'marketing.reports.upsale',
        'legacy_paths' => ['/ld/thong-ke/bao-cao-up-sale'],
    ],
    'kho-1' => [
        'menu_code' => '6.3.1',
        'title' => 'CEO dashboard',
        'admin_path' => '/admin/accounting/reports/ceo-dashboard',
        'route_name' => 'accounting.reports.ceo-dashboard',
        'legacy_paths' => ['/ld/ceo/dash-board', '/bao-cao/ceo-dash-board'],
    ],
    'warehouse-sales-summary' => [
        'menu_code' => '6.3.2',
        'title' => 'Báo cáo doanh số',
        'admin_path' => '/admin/warehouse/reports/revenue',
        'route_name' => 'warehouse.reports.revenue',
        'legacy_paths' => ['/ld/accounting/bao-cao/bao-cao-doanh-so'],
    ],
    'warehouse-sales-v2' => [
        'menu_code' => '6.3.3',
        'title' => 'Báo cáo doanh số V2',
        'admin_path' => '/admin/warehouse/reports/revenue-v2',
        'route_name' => 'warehouse.reports.revenue-v2',
        'legacy_paths' => ['/ld/warehouse/bao-cao/bao-cao-doanh-so-v2'],
    ],
    'product-conversion' => [
        'menu_code' => '6.3.9',
        'title' => 'Báo cáo tỉ lệ chốt đơn sản phẩm',
        'admin_path' => '/admin/reports/product-conversion',
        'route_name' => 'reports.product-conversion',
        'legacy_paths' => ['/ld/thong-ke/bao-cao-ti-le-chot-don-san-pham'],
    ],
];
